### ISSUE TITLE
Sometimes the new sign ups push people already signed up down to the wait list

### ISSUE THREAD

**Issue by nickcedwards** [ctcit/trips#25]
See https://ctc.org.nz/index.php/trip-signup?goto=trip%2Fshowtrip/627

This trip has a maximum of 15 participants, and was full. A week after the last person signed up, someone else signed up. The expected behaviour is that they would go on the wait list. What actually happened was that they were placed at 13 on the signup list, pushing the person previously at 15 down to the wait list.

**Comment by nickcedwards** [comment]
Looks like whenever new signs up it pushes the last person on the on-trip list down to the wait-list. Perhaps the priority value of the person at the bottom of the on-trip list has been assigned a too low priority for some reason?

**Comment by ghost** [comment]
@nickcedwards  Can you reproduce this easily?  I had several attempts but it worked just fine for me.  There must be something I'm missing.

**Comment by nickcedwards** [comment]
I haven't reproduced it in a dev environment but for the linked trip it
happens all the time. Maybe the database entries for that trip might show
what is going on?

**Comment by brucejames** [comment]
Okay.. I can't reproduce the problem on that trip but I can see that the displayPriority property for some participants on that trip is dodgy. Will look into the history to see if I can figure out what happened.

**Comment by brucejames** [comment]
Think I've found the issue and am implementing a fix.

**Comment by brucejames** [comment]
Fix pushed and deployed 3-Aug-2019
