### ISSUE TITLE
Trip email not working or not implemented?

### ISSUE THREAD

**Issue by trampgeek** [ctcit/trips#8]
See ctcit email of 14/12.

-- Richard

**Comment by brucejames** [comment]
I pushed the email handling client fixes to AlistairsDev branch.  I believe the server is getting what it expects but I still don't get any emails.  Any ideas Alistair?

**Comment by alastairgbrown** [comment]
fixed in this [commit](https://github.com/ctcit/trips/commit/38f240c18762842ddacdd1f3d3e1efbaf6196338)
